id: A8C60F808
title: f7E9E
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:38:17.065997
  last_modified_at: 2022-05-27 19:38:17.066000
