id: A8C60F808
title: f0A5A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:38:16.895504
  last_modified_at: 2022-05-27 19:38:16.895512
