id: A8C60F808
title: fB05A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:38:17.101403
  last_modified_at: 2022-05-27 19:38:17.101406
