id: A8C60F808
title: fE080
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:38:17.117120
  last_modified_at: 2022-05-27 19:38:17.117123
